# Generated by Django 2.0.2 on 2018-06-02 11:53

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import json
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('ip', models.CharField(default=None, max_length=50, null=True)),
                ('data', annoying.fields.JSONField(default=None, deserializer=json.loads, null=True, serializer=annoying.fields.dumps)),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('short_url', models.SlugField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('long_url', models.URLField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hit',
            name='url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='url_shorter.URL'),
        ),
    ]
