# Generated by Django 2.0.2 on 2018-06-02 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('short_url', models.SlugField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('long_url', models.URLField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
